name: ecommerce_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  internet_connection_checker: ^1.0.0
  dio: ^5.2.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  http: ^1.2.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
